### ISSUE TITLE
'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by kiranran** [yashas123/animepahe-downloader#5]
I tried downloading many different anime, but i keep getting the same error.

Traceback (most recent call last):
  File "series.py", line 449, in run
  File "series.py", line 458, in download_episode
AttributeError: 'NoneType' object has no attribute 'attrs'

**Comment by modbender** [comment]
Please give an example anime url

**Comment by kiranran** [comment]
https://animepahe.com/anime/kyokou-suiri

**Comment by modbender** [comment]
Fixed, could you please try downloading @kiranran

**Comment by kiranran** [comment]
I tried and this error appear when i press get episodes for any anime like the one above.

Traceback (most recent call last):
  File "series.py", line 200, in populate_episodes
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=nssFailure2&u=https%3A//animepahe.com/anime/kyokou-suiri&c=UTF-8&f=regular&d=The%20connection%20to%20animepahe.com%20was%20interrupted%20while%20the%20page%20was%20loading.

**Comment by modbender** [comment]
Ok, now this error happens because of problems from your side, either geckdriver.exe is closed when it's opened, either you don't have proper version of firefox or internet problems. That's atleast what the internet says.

**Comment by kiranran** [comment]
I've used VPN, different connection and also latest Firefox version and geckodriver but to no avail. This is the log from geckodriver.

https://throwbin.io/YQ5rEL5

**Comment by modbender** [comment]
Did you not give it permissions for firewall?
It would look something similar to this: 
![Image description](https://filestore.community.support.microsoft.com/api/images/d3ffb06b-fe33-4fa5-b8dd-7b3b24e38208)

**Comment by kiranran** [comment]
Already did, both firefox and series.

**Comment by uali6981** [comment]
I have same issue.

Log for error
![Annotation 2020-03-24 035822](https://user-images.githubusercontent.com/56256581/77420136-c0728f80-6d86-11ea-8aeb-4ec3430c770a.png)


For Path
![Annotation 2020-03-24 041307](https://user-images.githubusercontent.com/56256581/77420185-d41df600-6d86-11ea-856a-9fc86b3d5a98.png)


For `series` Firewall
![Annotation 2020-03-24 041339](https://user-images.githubusercontent.com/56256581/77420231-e6982f80-6d86-11ea-8002-908014642329.png)


For `Firefox` Firewall
![Annotation 2020-03-24 041357](https://user-images.githubusercontent.com/56256581/77420257-f3b51e80-6d86-11ea-83dc-70bd891501e2.png)


`Please help`
